baseURL = "https://jloh.codes"
languageCode = "en-AU"
title = "jloh.codes"
theme = "github_list"

[params]
  description  = "James' [GitHub](https://github.com/jloh) repos"
  github_repos = [
    "jloh"
  ]
